import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";
import Providers from "./components/Providers";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossOrigin="anonymous"
        />
        {/* <ReduxProvider>{children}<ReduxProvider> */}

        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
